name: Version bump
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version'
        required: true
jobs:
  version-bump:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependancies
        run: yarn install
      - name: Build source code
        run: yarn build-github
      - name: Setup Git
        run: |
           git config user.name gkr-bot
           git config user.email gkr@tuta.io
      - name: Version bump on package.json
        run: yarn version --new-version ${{ github.event.inputs.tag_name }} --no-git-tag-version
      - name: Commit the changes
        run: |
          git add ./dist ./package.json
          git commit -m "[skip-ci] Published ${{ github.event.inputs.tag_name }}"
      - name: Push to repository
        run: git push --quiet
